---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [meters-to-ha]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    #secrets: inherit
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
