---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@meters-to-ha
      - name: Set version number
        run: >-
          python3
          ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py
          --version ${{ steps.version.outputs.version }}
      - name: Create zip
        run: |
          cd apps/meters_to_ha
          zip MetersToHA.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./apps/meters_to_ha/MetersToHA.zip
          asset_name: MetersToHA.zip
          tag: ${{ github.ref }}
          overwrite: true
