---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches: [meters-to-ha]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: github.ref != 'refs/heads/meters-to-ha'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
